<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
      <PackageReference Include="CSharpFunctionalExtensions" />
      <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    </ItemGroup>
  
  <PropertyGroup>
    <PackageId>IstredDev.SharedKernel</PackageId>
    <Version>0.0.3</Version>
    <Authors>Istred</Authors>
    <Company>Istred</Company>
    <PackageDescription>SharedKernel</PackageDescription>
    <RepositoryUrl>https://github.com/EugenTovarchi/SharedService</RepositoryUrl>
  </PropertyGroup>

</Project>
